config/routes.rb
Rails.application.routes.draw do
  # デバイス用のルーティング
  devise_for :users
  # ルートパス
  root 'homes#top'
  get '/about' => 'homes#about'
  # ユーザーのルーティング
  # relationを入れ子構造に
  get 'users/sort' => 'users#sort'
  resources :users, only:[:index, :show, :edit, :update] do
    resources :relations, only:[:create, :destroy]
  end
  put '/users/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'
  put '/users/:id/back' => 'users#back', as: 'user_back'

  get 'museums/sort' => 'museums#sort'
  resources :museums do
    resources :posts, only:[:create, :edit, :update, :destroy] do
      resources :favorites, only:[:create, :destroy]
    end
    resources :recommends, only:[:create, :destroy]
    resources :visits, only:[:create, :destroy]
  end
  get 'map' => 'museums#map'

  resources :genres, only:[:create, :index, :destroy]

  resources :forums, only:[:create, :index, :show, :destroy] do
    resources :forum_posts, only:[:create]
  end
  get 'forums/:id/chat' => 'forums#chat', as: 'forum_chat'
  post 'forums/:id/lock' => 'forums#lock', as: 'forum_lock'

  get 'search' => 'searches#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
# ↓バリデーション
  validates :name, presence: true
# ↑バリデーション
  has_many :museums
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :if_not_admin

  def create
    @genre = Genre.new(params_genre)
    @genres = Genre.all
    unless @genre.save
      render 'index'
    end
  end

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    @genre = Genre.new
    @genres = Genre.all
  end

  private

  def params_genre
    params.require(:genre).permit(:name)
  end

  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_genres.html.erb
<thead>
  <tr>
    <th>ジャンル名</th>
    <th>施設数</th>
    <th></th>
  </tr>
</thead>
<tbody>
  <% genres.each do |genre| %>
    <tr>
      <td><%= genre.name %></td>
      <td><%= genre.museums.count %>件</td>
      <td><%= link_to '削除', genre_path(genre.id), method: :delete, remote: true, class:"btn btn-danger" %></td>
    </tr>
  <% end %>
</tbody>

app/views/genres/create.js.erb
$(".genres").html("<%= j(render 'genres', genres: @genres) %>");
$("#genre_name").val("");

app/views/genres/destroy.js.erb
$(".genres").html("<%= j(render 'genres', genres: @genres) %>");

app/views/genres/index.html.erb
<div class="page-title">
  <h3 class="mr-3">
    <i class="fas fa-marker"> ジャンル一覧</i>
  </h3>
</div>

<div class="mb-3">
  <%= form_with model:@genre do |f| %>
    <%= render "layouts/error_messages", resource: @genre %>
    <%= f.text_field :name %>
    <%= f.submit 'ジャンル登録', class:"btn btn-primary" %>
  <% end %>
</div>

<div class="genre-index">
  <table class="genres table">
    <%= render 'genres', genres: @genres %>
  </table>
</div>