config/routes.rb
Rails.application.routes.draw do
  # デバイス用のルーティング
  devise_for :users
  # ルートパス
  root 'homes#top'
  get '/about' => 'homes#about'
  # ユーザーのルーティング
  # relationを入れ子構造に
  get 'users/sort' => 'users#sort'
  resources :users, only:[:index, :show, :edit, :update] do
    resources :relations, only:[:create, :destroy]
  end
  put '/users/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'
  put '/users/:id/back' => 'users#back', as: 'user_back'

  get 'museums/sort' => 'museums#sort'
  resources :museums do
    resources :posts, only:[:create, :edit, :update, :destroy] do
      resources :favorites, only:[:create, :destroy]
    end
    resources :recommends, only:[:create, :destroy]
    resources :visits, only:[:create, :destroy]
  end
  get 'map' => 'museums#map'

  resources :genres, only:[:create, :index, :destroy]

  resources :forums, only:[:create, :index, :show, :destroy] do
    resources :forum_posts, only:[:create]
  end
  get 'forums/:id/chat' => 'forums#chat', as: 'forum_chat'
  post 'forums/:id/lock' => 'forums#lock', as: 'forum_lock'

  get 'search' => 'searches#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/forum.rb
class Forum < ApplicationRecord
  belongs_to :user
  has_many :forum_users, dependent: :destroy
  has_many :users, through: :forum_users
  has_many :forum_posts, dependent: :destroy
  accepts_nested_attributes_for :forum_users

  def membered?(current_user)
    forum_users.where(user_id: current_user.id).exists?
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_forum, only:[:show, :destroy, :chat, :lock]

  def create
    forum = Forum.new(forum_params)
    forum.user_id = current_user.id
      if    params[:forum][:date] == "undecided"
        forum.when = "未定"
      elsif params[:forum][:date] == "decided"
        forum.when = params[:forum][:when]
      end
    forum.save
    redirect_to forum_chat_path(forum.id)
  end

  def index
    @forums = Forum.all.order(id:"DESC").page(params[:page]).per(15)
    @forum = Forum.new
    @forum.users << current_user
  end

  def show
  end

  def chat
    if !@forum.users.include?(current_user)
      @forum.users << current_user
    end
    @forum_post = current_user.forum_posts.new
    @forum_posts = ForumPost.where(forum_id: @forum.id).all
  end

  def destroy
    @forum.destroy
    @forums = Forum.all.order(id:"DESC")
    redirect_to forums_path
  end

  def lock
    if @forum.lock == false
      @forum.lock = true
    else
      @forum.lock = false
    end
    @forum.save
    @forums = Forum.all.order(id:"DESC")
  end

  private

  def forum_params
    params.require(:forum).permit(:title, :body, :where, :when, :user_id => [])
  end

  def forum_post_params
    params.require(:forum_post).permit(:message)
  end

  def set_forum
    @forum = Forum.find(params[:id])
  end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_chat_posts.html.erb
<% forum_posts.each do |forum_post| %>
  <% if forum_post.user == current_user %>
    <div class="forum-right d-flex pr-5">
      <div class="forum-message">
        <%= forum_post.message %>
      </div>
    </div>
  <% else %>
    <div class="m-0 p-0 pl-2">
      <%= forum_post.user.name %>
    </div>
    <div class="forum-left d-flex mt-0 mb-0">
      <div class="user-icon pl-2">
        <%= attachment_image_tag forum_post.user, :profile_image, size:'40x40', format: 'jpeg', fallback:"no_image.png", class:"circle-image" %>
      </div>
      <div class="forum-message others-message">
        <%= forum_post.message %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/forums/_forum.html.erb
  <div class="d-flex forum-top">
    <div class="d-flex forum-key">
      <% if forum.lock == true %>
        <i class="fas fa-lock fa-lg key"></i>
      <% else %>
        <i class="fas fa-lock-open fa-lg unlocked-key"></i>
      <% end %>
    </div>
    <div class="d-flex ml-auto mr-auto forum-nail">
      <h4>●　</h4>
    </div>
  </div>
  <table class="table forum">
    <thead>
      <tr align="center">
        <th colspan="2" class="forum-title">
          <%= forum.title %>
        </th>
      </tr>
    </thead>
    <tbody>
      <tr align="center">
        <th colspan="2">
          <%= forum.users.count %>人が参加中！
        </th>
      </tr>
      <tr>
        <th class="forum-detail">訪問予定地：</th>
        <td><%= forum.where %></td>
      </tr>
      <tr>
        <th>訪問予定日：</th>
        <td><%= forum.when %></td>
      </tr>
      <tr>
        <th>ひとこと：</th>
        <td><%= forum.body %></td>
      </tr>
      <% if forum.lock == true %>
        <tr class="forum-button">
          <% if forum.membered?(current_user) %>
            <td colspan="2" align="center">
              <%= link_to forum_chat_path(forum.id), class:"btn btn-success" do %>
                <i class="fas fa-users"></i>
                チャットに戻る！
              <% end %>
            </td>
          <% end %>
        </tr>
        <tr>
          <td colspan="2" align="center">
            <%= link_to forum_path(forum.id) do %>
              <i class="fas fa-question-circle"></i>
              詳細
            <% end %>
            <% if forum.user_id == current_user.id %>
              <%= link_to forum_lock_path(forum.id), method: :post, remote: true do %>
                <i class="fas fa-key"></i>
                鍵をはずす
              <% end %>
              <%= link_to forum_path(forum.id), method: :delete do %>
                <i class="far fa-trash-alt"></i>
                削除
              <% end %>
            <% end %>
          </td>
        </tr>
      <% else %>
        <tr class="forum-button">
          <% if forum.membered?(current_user) %>
            <td colspan="2" align="center">
              <%= link_to forum_chat_path(forum.id), class:"btn btn-success" do %>
                <i class="fas fa-users"></i>
                チャットに戻る！
              <% end %>
            </td>
          <% else %>
            <td colspan="2" align="center">
              <%= link_to forum_chat_path(forum.id), class:"btn btn-primary" do %>
                <i class="fas fa-users"></i>
                参加する！
              <% end %>
            </td>
          <% end %>
        </tr>
        <tr>
          <td colspan="2" align="center">
            <%= link_to forum_path(forum.id) do %>
              <i class="fas fa-question-circle"></i>
              詳細
            <% end %>
            <% if forum.user_id == current_user.id %>
              <%= link_to forum_lock_path(forum.id), method: :post, remote: true do %>
                <i class="fas fa-key"></i>
                鍵をかける
              <% end %>
              <%= link_to forum_path(forum.id), method: :delete do %>
                <i class="far fa-trash-alt"></i>
                削除
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/forums/_forums.html.erb
<% forums.each do |forum| %>
  <% if forum.user.is_deleted == false %>
    <div class="pt-2 pr-2 pb-0 pl-2 mr-4 mb-4 col-md-5 forum-description">
      <div class="d-flex forum-top">
        <div class="d-flex forum-key">
          <% if forum.lock == true %>
            <i class="fas fa-lock fa-lg key"></i>
          <% else %>
            <i class="fas fa-lock-open fa-lg unlocked-key"></i>
          <% end %>
        </div>
        <div class="d-flex ml-auto mr-auto forum-nail">
          <h4>●　</h4>
        </div>
      </div>
      <table class="table forum">
        <thead>
          <tr class="forum-title" align="center">
            <th colspan="2">
              <%= link_to forum_path(forum.id) do %>
                <%= forum.title %>
              <% end %>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr class="forum-letter">
            <td width="130">訪問予定地：</td>
            <th class="pl-0 pr-0"><%= forum.where %></th>
          </tr>
          <tr class="forum-letter">
            <td>訪問予定日：</td>
            <th class="pl-0 pr-0"><%= forum.when %></th>
          </tr>
          <tr class="forum-letter">
            <td>ひとこと　：</td>
            <th class="pl-0 pr-0"><%= forum.body %></th>
          </tr>
          <% if forum.lock == true %>
            <tr class="forum-button">
              <% if forum.membered?(current_user) %>
                <td colspan="2" align="center">
                  <%= link_to forum_chat_path(forum.id), class:"btn btn-success" do %>
                    <i class="fas fa-users"></i>
                    チャットに戻る！
                  <% end %>
                </td>
              <% end %>
            </tr>
            <tr>
              <td colspan="2" align="center">
                <%= link_to forum_path(forum.id) do %>
                  <i class="fas fa-question-circle"></i>
                  詳細
                <% end %>
                <% if forum.user_id == current_user.id %>
                  <%= link_to forum_lock_path(forum.id), method: :post, remote: true do %>
                    <i class="fas fa-key"></i>
                    鍵をはずす
                  <% end %>
                  <%= link_to forum_path(forum.id), method: :delete, remote: true do %>
                    <i class="far fa-trash-alt"></i>
                    削除
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% else %>
            <tr class="forum-button">
              <% if forum.membered?(current_user) %>
                <td colspan="2" align="center">
                  <%= link_to forum_chat_path(forum.id), class:"btn btn-success" do %>
                    <i class="fas fa-users"></i>
                    チャットに戻る！
                  <% end %>
                </td>
              <% else %>
                <td colspan="2" align="center">
                  <%= link_to forum_chat_path(forum.id), class:"btn btn-primary" do %>
                    <i class="fas fa-users"></i>
                    参加する！
                  <% end %>
                </td>
              <% end %>
            </tr>
            <tr>
              <td colspan="2" align="center">
                <%= link_to forum_path(forum.id) do %>
                  <i class="fas fa-question-circle"></i>
                  詳細
                <% end %>
                <% if forum.user_id == current_user.id %>
                  <%= link_to forum_lock_path(forum.id), method: :post, remote: true do %>
                    <i class="fas fa-key"></i>
                    鍵をかける
                  <% end %>
                  <%= link_to forum_path(forum.id), method: :delete, remote: true do %>
                    <i class="far fa-trash-alt"></i>
                    削除
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
<% end %>

app/views/forums/chat.html.erb
<div class="page-title d-flex">
  <h3>
    <i class="fas fa-comments">
       <%= @forum.title %>
    </i>
  </h3>
  <div class="pl-2">
    <% if @forum.lock == true %>
      <i class="fas fa-lock fa-lg key"></i>
    <% else %>
      <i class="fas fa-lock-open fa-lg unlocked-key"></i>
    <% end %>
  </div>
</div>

<% if @forum.user.is_deleted == false %>
  <div class="row">
    <div class="col-md-3">
      <div>
        <h4>参加メンバー</h4>
          <table>
            <% @forum.users.each do |user| %>
              <tr>
                <td>
                  <% if @forum.user_id == user.id %>
                    <i class="fas fa-chalkboard-teacher"></i>
                    作成者
                  <% end %>
                </td>
                <th>
                  <%= link_to user_path(user.id) do %>
                    <%= attachment_image_tag user, :profile_image, size: '40x40', format: 'jpeg', fallback:"no_image.png" %>
                    <%= user.name %>
                  <% end %>
                </th>
              </tr>
            <% end %>
          </table>
      </div>
    </div>

    <div class="col-md-9 forum-post">
      <div class="forum-post-display" id="scroll-inner">
        <%= render 'chat_posts', forum_posts: @forum_posts %>
      </div>
      <div>
        <%= form_with model:@forum_post, url:forum_forum_posts_path(@forum) do |f| %>
          <div class="forum-post-form d-flex align-items-center">
            <div class="p-2">
              <%= f.text_area :message, size:"95%" %>
            </div>
            <div>
              <%= f.submit '送信', class:"btn btn-outline-success" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <h3>ページが存在しません！</h3>
<% end %>

app/views/forums/destroy.js.erb
$(".forums").html("<%= j(render 'forums', forums: @forums) %>");

app/views/forums/index.html.erb
<div class="page-title">
  <h3>
    <i class="fas fa-clipboard-list"> 掲示板</i>
  </h3>
</div>

<div class="row">
  <div class="forum-form">
    <%= form_with model:@forum do |f| %>
      <strong><%= f.label :title, 'タイトル' %></strong><br/>
      　<%= f.text_field :title, class:"mb-2" %><br/>

      <strong><%= f.label :where, '訪問予定地' %></strong><br/>
      　<%= f.text_field :where, class:"mb-2" %><br/>

      <strong><%= f.label :when, '訪問予定日' %></strong><br/>
      　<%= f.radio_button :date, 'undecided', checked: true %>
      　<%= f.label :date, '未定' %><br/>
      　<%= f.radio_button :date, 'decided' %>
      　<%= f.label :date, '日時指定' %><br/>
      　　<%= f.date_field :when, class:"mb-2" %><br/>

      <strong><%= f.label :body, 'ひとこと' %></strong><br/>
      　<%= f.text_area :body, class:"mb-2" %><br/>

    <%= f.submit '掲示板を作成する', class:"btn btn-success" %>
    <% end %>
  </div>

  <div class="col-md-3"></div>
  <div class="col-md-9">
    <div class="row forums">
      <%= render 'forums', forums: @forums %>
    </div>
    <%= paginate @forums %>
  </div>
</div>

app/views/forums/lock.js.erb
$(".forums").html("<%= j(render 'forums', forums: @forums) %>");

$(".forum-descriptions").html("<%= j(render 'forum', forum: @forum) %>");

app/views/forums/show.html.erb
<div class="page-title">
  <h3>
    <i class="fas fa-clipboard-list"> 掲示板詳細</i>
  </h3>
</div>

<div class="row">
  <div class="col-md-3">
    <!--ユーザー詳細画面のサイドバー：基本情報を表示-->
    <h5 class="mb-5"><strong>掲示板を作ったひと</strong></h5>
    <table>
      <tr align="center">
        <th colspan="2"><%= attachment_image_tag @forum.user, :profile_image, size:"80x80", format:"jpeg", fallback:"no_image.png", class:"circle-image" %></th>
        <th></th>
      </tr>
      <tr align="center">
        <th colspan="2"><%= @forum.user.name %></th>
        <th></th>
      </tr>
      <tr>
        <th>　</th>
        <td>　</td>
      </tr>
      <tr>
        <th>行った博物館</th>
        <td>　<%= @forum.user.visits.count %> 軒</td>
      </tr>
      <tr>
        <th>おすすめした博物館</th>
        <td>　<%= @forum.user.recommends.count %> 軒</td>
      </tr>
      <tr>
        <td>　</td>
        <td>　</td>
      </tr>
      <% if @forum.user.introduction != nil %>
        <tr align="center">
          <th colspan="2">自己紹介</th>
          <td></td>
        </tr>
      <% end %>
      <tr>
        <td colspan="2"><%= @forum.user.introduction %></td>
        <td></td>
      </tr>
      <tr>
        <td>　</td>
      </tr>
      <tr align="center">
        <th colspan="2">
          <% if @forum.user != current_user %>
            <% if @forum.user.followed_by?(current_user) %>
              <%= link_to 'フォロー中', user_relation_path(@forum.user.id, @forum.user.id), method: :delete, class:"btn btn-success" %>
            <% else %>
              <%= link_to 'フォロー', user_relations_path(@forum.user.id), method: :post, class:"btn btn-primary" %>
            <% end %>
          <% end %>
        </th>
        <td></td>
      </tr>
      <tr>
        <td>　</td>
        <td>　</td>
      </tr>
      <% if @forum.user == current_user %>
        <tr align="center">
          <th colspan="2">
            <%= link_to edit_user_path(current_user), class:"btn btn-outline-success btn-block" do %>
              <i class="fas fa-user-edit"></i>
              編集
            <% end %>
          </th>
          <td></td>
        </tr>
        <tr>
          <td>　</td>
        </tr>
        <tr align="center">
          <th colspan="2">
            <%= link_to user_withdraw_path(current_user), method: :put, "data-confirm" => "本当に退会しますか？", class:"btn btn-outline-danger" do %>
              <i class="fas fa-running"></i>
              退会
            <% end %>
          </th>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="forum-descriptions pt-2 pr-2 pb-0 pl-2 mr-4 mb-4 col-md-8">
    <%= render 'forum', forum: @forum %>
  </div>
</div>