config/routes.rb
Rails.application.routes.draw do
  # デバイス用のルーティング
  devise_for :users
  # ルートパス
  root 'homes#top'
  get '/about' => 'homes#about'
  # ユーザーのルーティング
  # relationを入れ子構造に
  get 'users/sort' => 'users#sort'
  resources :users, only:[:index, :show, :edit, :update] do
    resources :relations, only:[:create, :destroy]
  end
  put '/users/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'
  put '/users/:id/back' => 'users#back', as: 'user_back'

  get 'museums/sort' => 'museums#sort'
  resources :museums do
    resources :posts, only:[:create, :edit, :update, :destroy] do
      resources :favorites, only:[:create, :destroy]
    end
    resources :recommends, only:[:create, :destroy]
    resources :visits, only:[:create, :destroy]
  end
  get 'map' => 'museums#map'

  resources :genres, only:[:create, :index, :destroy]

  resources :forums, only:[:create, :index, :show, :destroy] do
    resources :forum_posts, only:[:create]
  end
  get 'forums/:id/chat' => 'forums#chat', as: 'forum_chat'
  post 'forums/:id/lock' => 'forums#lock', as: 'forum_lock'

  get 'search' => 'searches#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

# ↓バリデーション
  validates :name, presence: true, length: {in: 1..10}, uniqueness: true
# ↑バリデーション
  attachment :profile_image
  attachment :picture

  has_many :active_relations, class_name: "Relation", foreign_key: :following_id, dependent: :destroy
  has_many :followings, through: :active_relations, source: :followed
  has_many :passive_relations, class_name: "Relation", foreign_key: :followed_id, dependent: :destroy
  has_many :followeds, through: :passive_relations, source: :following
  has_many :recommends, dependent: :destroy
  has_many :recommended_museums, through: :recommends, source: :museum
  has_many :visits, dependent: :destroy
  has_many :visited_museums, through: :visits, source: :museum
  has_many :favorites
  has_many :posts, dependent: :destroy
  has_many :post_images, through: :posts
  has_many :forum_posts, dependent: :destroy
  has_many :forum_users, dependent: :destroy
  has_many :forums, through: :forum_users
  has_many :museums
  has_many :active_notifications, class_name: "Notification", foreign_key: :visitor_id, dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: :visited_id, dependent: :destroy

  def followed_by?(user)
    passive_relations.find_by(following_id: user.id).present?
  end

  def forum_host?(user)
    forums = Forum.where(lock: false)
    forums.where(user_id: user.id).exists?
  end

  def self.looks(searches, words)
    if searches == "perfect_match"
      @user = User.where("name LIKE ?", "#{words}")
    elsif searches == "partial_match"
      @user = User.where("name LIKE ?", "%#{words}%")
    end
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ?", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :user_set, only:[:show, :edit, :update, :withdraw, :back]

  def index
    @users = User.page(params[:page]).per(20)
  end

  def show
    @my_posts    = Post.where(user_id: @user.id).order(id: "DESC")
    @visits      = Visit.where(user_id: current_user.id)
    @museums     = Museum.all.order(:prefecture)
    @forum_users = ForumUser.where(user_id: params[:id])
    @followings  = @user.followings
    @followeds   = @user.followeds
    # 通知関係↓
    @notifications = current_user.passive_notifications.all
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
    @created_museums = Museum.where(status: 1).last(5)
    @updated_museums = Museum.where(status: 2).last(5)
    # ここまで
  end

  def edit
  end

  def update
    if @user.update(params_user)
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end

  def withdraw
    @user.update(is_deleted: true)
    unless current_user.admin?
      reset_session
      redirect_to root_path
    end
    @users = User.all
  end

  def back
    @user.update(is_deleted: false)
    @users = User.all
  end

  def sort
    if params[:sort] == "recommend"
      @users = User.all.sort{|a,b| b.recommends.count <=> a.recommends.count}
      @sort = "recommend"
    elsif params[:sort] == "visit"
      @users = User.all.sort{|a,b| b.visits.count <=> a.visits.count}
      @sort = "visitor"
    elsif params[:sort] == "post"
      @users = User.all.sort{|a,b| b.posts.count <=> a.posts.count}
      @sort = "comment"
    elsif params[:sort] == "picture"
      @users = User.all.sort{|a,b| b.post_images.count <=> a.post_images.count}
      @sort = "picture"
    end
  end

  private

  def user_set
    @user = User.find(params[:id])
  end

  def params_user
    params.require(:user).permit(:profile_image, :name, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<% if user.followed_by?(current_user) %>
  <%= link_to 'フォロー中', user_relation_path(user.id, user.id), method: :delete, remote: true, class:"btn btn-success" %>
<% else %>
  <%= link_to 'フォロー', user_relations_path(user.id), method: :post , remote: true, class:"btn btn-primary"%>
<% end %>

app/views/users/_follow_tab.html.erb
<div>
  <h5><strong>フォロー</strong></h5>
  <% if followings.exists? %>
    <table class="table">
      <tr align="center">
        <th></th>
        <th></th>
        <th>訪問軒数</th>
        <th>おすすめ</th>
        <th>コメント数</th>
        <th>写真数</th>
      </tr>
      <% followings.each do |following| %>
        <tr align="center">
          <td><%= attachment_image_tag following, :profile_image, size:"40x40", format:"jpeg", fallback:"no_image.png" %></td>
          <td><%= following.name %></td>
          <td><%= following.visits.count %> 軒</td>
          <td><%= following.recommends.count %> 軒</td>
          <td><%= following.posts.count %> 件</td>
          <td><%= following.post_images.count %> 枚</td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <p>　フォローしている人はいません！</p>
  <% end %>
</div>
<div>
  <h5><strong>フォロワー</strong></h5>
  <% if followeds.exists? %>
    <table class="table">
      <tr align="center">
        <th></th>
        <th></th>
        <th>訪問軒数</th>
        <th>おすすめ</th>
        <th>コメント数</th>
        <th>写真数</th>
      </tr>
      <% followeds.each do |followed| %>
      <tr align="center">
        <td><%= attachment_image_tag followed, :profile_image, size:"40x40", format:"jpeg", fallback:"no_image.png" %></td>
        <td><%= followed.name %></td>
        <td><%= followed.visits.count %> 軒</td>
        <td><%= followed.recommends.count %> 軒</td>
        <td><%= followed.posts.count %> 件</td>
        <td><%= followed.post_images.count %> 枚</td>
      </tr>
      <% end %>
    </table>
  <% else %>
    <p>　フォローされている人はいません！</p>
  <% end %>
</div>

app/views/users/_post.html.erb
<div class="post-title d-flex">
  <div class="post-main_title">
    <strong><%= post.title %></strong>
    <span>
    　<%= link_to museum_path(post.museum.id) do %>
    　 ＠<%= post.museum.name %>
    　<% end %>
    </span>
  </div>
  <div class="post-user">
    <%= link_to user_path(post.user.id) do %>
      <%= attachment_image_tag post.user, :profile_image, size:"40x40", format:"jpeg", fallback:"no_image.png", class:"circle-image" %>
    <% end %>
    <%= post.user.name %>
  </div>
</div>
<div class="post-body">
  <%= post.body %><br/>
  <!--画像が投稿されていた場合に画像表示-->
  <% if post.post_images.present? %>
    <% post.post_images.each do |image| %>
      <%= attachment_image_tag image, :picture, size:"40x40", format:"jpeg" %>
    <% end %>
  <% end %>
</div>
<div class="post-detail d-flex">
  <div>
    <% if post.how_to_visit.present? %>
      <label>訪問方法：</label>
      <%= post.how_to_visit %>
    <% end %>
    <% if post.companion.present? %>
      <label>同伴者：</label>
      <%= post.companion %>
    <% end %>
  </div>
  <div class="post-day d-flex pl-2">
    <% if post.user == current_user %>
      <div class="mr-4">
        <label>投稿日：</label>
        <%= post.created_at.strftime('%Y/%m/%d') %>
      </div>
      <div class="mr-3">
        <i class="fas fa-heart fa-lg my-heart"></i>
        <%= post.favorites.count %>
      </div>
      <div class="mr-1">
        <%= link_to edit_museum_post_path(post.museum.id, post.id) do %>
          <i class="far fa-edit fa-lg"></i>
          編集
        <% end %>
      </div>
      <div>
        <%= link_to museum_post_path(post.museum.id, post.id), method: :delete, remote: true do %>
          <i class="far fa-trash-alt fa-lg"></i>
          削除
        <% end %>
      </div>
    <% else %>
      <div class="d-flex">
        <div class="mr-4">
          <label>投稿日：</label>
          <%= post.created_at.strftime('%Y/%m/%d') %>
        </div>
        <div>
          <% if post.favorited_by?(current_user) %>
            <%= link_to museum_post_favorite_path(post.museum.id, post.id, post.id), method: :delete, remote: true do %>
              <i class="fas fa-heart fa-lg like-heart"></i>
            <% end %>
            <%= post.favorites.count %>
          <% else %>
            <%= link_to museum_post_favorites_path(post.museum.id, post.id), method: :post, remote: true do %>
              <i class="far fa-heart fa-lg unlike-heart"></i>
            <% end %>
            <%= post.favorites.count %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_posts.html.erb
<% my_posts.each do |post| %>
  <div class="post-index user-post_<%= post.id %>">
    <% if post.user.is_deleted == false %>
      <%= render 'users/post', post: post %>
    <% end %>
  </div>
<% end %>

app/views/users/_user_index.html.erb
<% users.each do |user| %>
  <tr align="center">
    <td>
      <% if user.forum_host?(user) %>
        <i class="fas fa-clipboard-list fa-lg clipboard"></i>
      <% end %>
    </td>
    <td align="left">
      <%= link_to user_path(user.id) do %>
        <%= attachment_image_tag user, :profile_image, size:"40x40", format:"jpeg", fallback:"no_image.png", class:"circle-image" %>
        <%= user.name %>
      <% end %>
    </td>
    <td><%= user.visits.count %>軒</td>
    <td><%= user.recommends.count %>軒</td>
    <td><%= user.posts.count %>件</td>
    <td><%= user.post_images.count %>枚</td>
    <td class="follow_<%= user.id %>">
      <% if user != current_user %>
          <%= render 'follow', user: user %>
      <% end %>
    </td>
    <td>
      <% if user.is_deleted == false %>
        <%= link_to '有効', user_withdraw_path(user.id), method: :put, remote: true, class:"btn btn-info" %>
      <% else %>
        <%= link_to '退会', user_back_path(user.id), method: :put, remote: true, class:"btn btn-danger" %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/users/back.js.erb
$(".user_index").html("<%= j(render 'users/user_index', users: @users ) %>");

app/views/users/edit.html.erb
<div class="page-title">
  <h3>
    <i class="fas fa-child"> プロフィール編集</i>
  </h3>
</div>

<%= render "layouts/error_messages", resource: @user %>

<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <% if @user.id == current_user.id %>
      <%= form_with model:@user, local:true do |f| %>
        <table class="table table-borderless">
          <tr>
            <th>
              <%= f.label :profile_image, 'アイコン画像' %>
            </th>
            <td>
              <%= f.attachment_field :profile_image %>
            </td>
          </tr>
          <tr>
            <th>
              <%= f.label :name, 'ニックネーム' %>
            </th>
            <td>
              <%= f.text_field :name %>
            </td>
          </tr>
          <tr>
            <th>
              <%= f.label :introduction, '自己紹介' %>
            </th>
            <td>
              <%= f.text_area :introduction, size:"40x5", placeholder:"空欄でも大丈夫です！" %>
            </td>
          </tr>
          <tr align="center">
            <th colspan="2">
              <%= f.submit 'プロフィール更新！', class:"btn btn-success" %>
            </th>
            <td></td>
          </tr>
        </table>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="page-title">
  <h3>
    <i class="fas fa-child"> ユーザー一覧</i>
  </h3>
</div>

<%= form_with url: users_sort_path, method: :get, local: true do |f| %>
  <%= f.select :sort,
  [['訪問数が多い順','visit'],
   ['おすすめが多い順','recommend'],
   ['コメント数が多い順','post'],
   ['写真数が多い順','picture']]
   %>
   <%= f.submit '並びかえる' %>
<% end %>

<div class="row">
  <table class="table">
    <thead>
      <tr align="center">
        <th></th>
        <th></th>
        <th>訪問軒数</th>
        <th>おすすめ軒数</th>
        <th>コメント数</th>
        <th>投稿写真数</th>
        <th></th>
        <% if current_user.admin? %>
          <th>
            ステータス
          </th>
        <% end %>
      </tr>
    </thead>
    <% if current_user.admin? %>
      <tbody class="user_index">
        <%= render 'user_index', users: @users %>
      </tbody>
    <% else %>
      <tbody>
        <% @users.each do |user| %>
          <% if user.is_deleted == false %>
            <tr align="center">
              <td>
                <% if user.forum_host?(user) %>
                  <i class="fas fa-clipboard-list fa-lg clipboard"></i>
                <% end %>
              </td>
              <td align="left">
                <%= link_to user_path(user.id) do %>
                  <%= attachment_image_tag user, :profile_image, size:"40x40", format:"jpeg", fallback:"no_image.png", class:"circle-image" %>
                  <%= user.name %>
                <% end %>
              </td>
              <td><%= user.visits.count %>軒</td>
              <td><%= user.recommends.count %>軒</td>
              <td><%= user.posts.count %>件</td>
              <td><%= user.post_images.count %>枚</td>
              <td class="follow_<%= user.id %>">
                <% if user != current_user %>
                    <%= render 'follow', user: user %>
                <% end %>
              </td>
              <% if current_user.admin? %>
                <td>
                  <% if user.is_deleted == false %>
                    <%= link_to '有効', user_withdraw_path(user.id), class:"btn btn-info" %>
                  <% else %>
                    <%= link_to '退会', user_back_path(user.id), class:"btn btn-danger" %>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    <% end %>
  </table>
</div>
<%= paginate @users %>

app/views/users/show.html.erb
<div class="page-title">
  <% if @user.is_deleted == false %>
    <% if @user != current_user %>
      <h3><i class="fas fa-child"> <%= @user.name %>さんのページ</i></h3>
    <% else %>
      <h3><i class="fas fa-child"> マイページ</i></h3>
    <% end %>
</div>

<div class="row">
  <div class="col-md-3">
    <!--ユーザー詳細画面のサイドバー：基本情報を表示-->
    <table>
      <tr align="center">
        <th colspan="2"><%= attachment_image_tag @user, :profile_image, size:"80x80", format:"jpeg", fallback:"no_image.png", class:"circle-image" %></th>
        <th></th>
      </tr>
      <tr align="center">
        <th colspan="2"><%= @user.name %></th>
        <th></th>
      </tr>
      <tr>
        <th>　</th>
        <td>　</td>
      </tr>
      <tr>
        <th>行った博物館</th>
        <td>　<%= @user.visits.count %> 軒</td>
      </tr>
      <tr>
        <th>おすすめした博物館</th>
        <td>　<%= @user.recommends.count %> 軒</td>
      </tr>
      <tr>
        <td>　</td>
        <td>　</td>
      </tr>
      <% if @user.introduction != nil %>
        <tr align="center">
          <th colspan="2">自己紹介</th>
          <td></td>
        </tr>
        <tr>
          <td colspan="2"><%= @user.introduction %></td>
          <td></td>
        </tr>
      <% end %>
      <% if @forum_users.present? %>
        <tr align="center">
          <th colspan="2">参加中の掲示板</th>
          <td></td>
        </tr>
        <% @forum_users.each do |forum_user| %>
          <tr>
            <td>
              <% if forum_user.forum.user_id == @user.id %>
                <i class="fas fa-chalkboard-teacher"></i>
              <% else %>
                <span>　</span>
              <% end %>
              <%= link_to forum_user.forum.title, forum_path(forum_user.forum.id) %>
            </td>
          </tr>
        <% end %>
      <% end %>
      <tr align="center">
        <th class="follow_<%= @user.id %>" colspan="2">
          <% if @user != current_user %>
            <%= render 'follow', user: @user %>
          <% end %>
        </th>
        <td></td>
      </tr>
      <tr>
        <td>　</td>
        <td>　</td>
      </tr>
      <% if @user == current_user %>
        <tr align="center">
          <th colspan="2">
            <%= link_to edit_user_path(current_user), class:"btn btn-outline-success btn-block" do %>
              <i class="fas fa-user-edit"></i>
              編集
            <% end %>
          </th>
          <td></td>
        </tr>
        <tr>
          <td>　</td>
        </tr>
        <tr align="center">
          <th colspan="2">
            <%= link_to user_withdraw_path(current_user), method: :put, "data-confirm" => "本当に退会しますか？", class:"btn btn-outline-danger" do %>
              <i class="fas fa-running"></i>
              退会
            <% end %>
          </th>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="col-md-9 wrap">
    <% if @user == current_user %>
      <ul id="tab-menu" class="mb-0">
        <li><a href="#top" class="active">お知らせ</a></li>
        <li><a href="#visit-museum" class="">行った博物館</a></li>
        <li><a href="#post" class="">投稿</a></li>
        <li><a href="#post-image" class="">アルバム</a></li>
        <li><a href="#follow" class="">フォロー</a></li>
      </ul>
    <% else %>
      <ul id="tab-menu" class="mb-0">
        <li><a href="#top" class="active">行った博物館</a></li>
        <li><a href="#post" class="">投稿</a></li>
        <li><a href="#post-image" class="">アルバム</a></li>
        <li><a href="#follow" class="">フォロー</a></li>
      </ul>
    <% end %>
    <div id="tab-contents">
      <!--自分以外のユーザーには通知が見えないように-->
      <% if @user == current_user %>
        <div id="top" class="tab">
          <!--各種通知表示-->
          <h4><strong>新着博物館(5軒)</strong></h4>
          <div class="mb-5">
            <h5>　登録</h5>
            <% if @created_museums.present? %>
              <% @created_museums.each do |museum| %>
                <table>
                  <tr>　　<%= museum.created_at.strftime('%Y/%m/%d') %></tr>
                  <tr>
                    <%= link_to user_path(museum.user.id) do %>
                      <% if museum.user.is_deleted == false %>
                        <span>　<%= museum.user.name %>さん</span>
                      <% else %>
                        <span>退会済みユーザー</span>
                      <% end %>
                    <% end %>
                    が
                  </tr>
                  <tr><%= link_to museum.name, museum_path(museum.id) %>を投稿しました！</tr>
                </table>
              <% end %>
            <% else %>
              <p>　　新規登録された博物館はありません</p>
            <% end %>
            <h5 class="mt-2">　編集</h5>
            <% if @updated_museums.present? %>
              <% @updated_museums.each do |museum| %>
                <table>
                  <tr>　　<%= museum.created_at.strftime('%Y/%m/%d') %></tr>
                  <tr>
                    <%= link_to user_path(museum.user.id) do %>
                      <% if museum.user.is_deleted == false %>
                        <span>　<%= museum.user.name %>さん</span>
                      <% else %>
                        <span>退会済みユーザー</span>
                      <% end %>
                    <% end %>
                    が
                  </tr>
                  <tr><%= link_to museum.name, museum_path(museum.id) %>を編集しました！</tr>
                </table>
              <% end %>
            <% else %>
              <p>　　編集された博物館はありません</p>
            <% end %>
          </div>
          <h4><strong>その他</strong></h4>
            <% notifications = @notifications.where.not(visitor_id: current_user.id) %>
            <% if notifications.exists? %>
              <%= render notifications %>
            <% else %>
              <p>　　通知はありません</p>
            <% end %>
        </div>
      <% end %>

      <% if @user == current_user %>
        <div id="visit-museum" class="tab">
      <% else %>
        <div id="top" class="tab">
      <% end %>
        <!--行った：訪問済み(行ったボタンを押した)施設の一覧表示-->
      <% if @visits.exists? %>
        <table class="table visited-museum">
          <tr align="center">
            <th></th>
            <th></th>
            <th></th>
            <th>所在県</th>
            <th>ジャンル</th>
            <th>訪問人数</th>
            <th>おすすめ</th>
            <th>コメント数</th>
            <th>写真数</th>
          </tr>
          <% @user.visits.each do |visit| %>
            <% museum = visit.museum %>
            <tr align="center">
              <td>
                <% if museum.recommended_by?(@user) %>
                  <i class="fas fa-star star"></i>
                <% elsif museum.visited_by?(@user) %>
                  <i class="fas fa-door-open door"></i>
                <% end %>
              </td>
              <td><%= attachment_image_tag museum, :appearance_image, size:"40x40", format:"jpeg" %></td>
              <td align="left" class="visited-museum-name">
                <%= link_to museum_path(museum.id) do %>
                  　<%= museum.name %>
                <% end %>
              </td>
              <td><%= museum.prefecture %></td>
              <td><%= museum.genre.name %></td>
              <td><%= museum.visits.count %> 人</td>
              <td><%= museum.recommends.count %> 人</td>
              <td><%= museum.posts.count %> 件</td>
              <td><%= museum.post_images.count %> 枚</td>
            </tr>
          <% end %>
        </table>
      <% else %>
        <p>訪問した博物館はありません！</p>
      <% end %>
      </div>

      <div id="post" class="tab">
        <div class="my-posts_index">
          <% if @my_posts.exists? %>
            <!--コメント：コメントの一覧表示-->
              <%= render 'users/posts', my_posts: @my_posts %>
          <% else %>
            <p>まだ投稿していません！</p>
          <% end %>
        </div>
      </div>

      <div id="post-image" class="tab">
        <% if @user.post_images.exists? %>
          <!--アルバム：投稿された写真の一覧表示-->
          <% @museums.each do |museum| %>
            <% museum.posted_by(@user).each do |post| %>
                <% if post.post_images.exists? %>
                  <h4 class="m-0 mt-3"><%= post.museum.name %></h4><br/>
                  <% post.post_images.each do |image| %>
                    <%= attachment_image_tag image, :picture, size:"100x100", format:"jpeg" %>
                  <% end %>
                <% end %>
            <% end %>
          <% end %>
        <% else %>
          <p>まだ写真を投稿していません！</p>
        <% end %>
      </div>

      <div id="follow" class="tab">
        <!--フォロー・フォロワー：フォローしている人、されている人の一覧表示-->
        <div class="follow_tab">
          <%= render partial: 'users/follow_tab', locals: {followings: @followings, followeds: @followeds} %>
        </div>
      </div>
    </div>
    <script defer="application.js"></script>
  </div>
</div>
<% else %>
  <h3>ページが存在しません！</h3>
<% end %>

app/views/users/sort.html.erb
<div class="page-title d-flex">
  <h3>
    <i class="fas fa-child"> ユーザー一覧</i>
  </h3>
  <p class="mr-3 mt-2">
    (<% if @sort == "visitor" %>
      訪問数が多い順
    <% elsif @sort == "recommend" %>
      おすすめが多い順
    <% elsif @sort == "comment" %>
      コメント数が多い順
    <% elsif @sort == "picture" %>
      写真数が多い順
    <% end %>)
  </p>
</div>

<%= form_with url: users_sort_path, method: :get, local: true do |f| %>
  <%= f.select :sort,
  [['訪問数が多い順','visit'],
   ['おすすめが多い順','recommend'],
   ['コメント数が多い順','post'],
   ['写真数が多い順','picture']]
   %>
   <%= f.submit '並びかえる' %>
<% end %>

<div class="row">
  <table class="table">
    <thead>
      <tr align="center">
        <th></th>
        <th></th>
        <th>訪問軒数</th>
        <th>おすすめ軒数</th>
        <th>コメント数</th>
        <th>投稿写真数</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    　<% @users.each do |user| %>
    　　<% if user.is_deleted == false %>
          <tr align="center">
            <td>
              <% if user.forum_host?(user) %>
                <i class="fas fa-clipboard-list fa-lg clipboard"></i>
              <% end %>
            </td>
            <td align="left">
              <%= link_to user_path(user.id) do %>
                <%= attachment_image_tag user, :profile_image, size:"40x40", format:"jpeg", fallback:"no_image.png", class:"circle-image" %>
                <%= user.name %>
              <% end %>
            </td>
            <td><%= user.visits.count %>軒</td>
            <td><%= user.recommends.count %>軒</td>
            <td><%= user.posts.count %>件</td>
            <td><%= user.post_images.count %>枚</td>
            <% if user != current_user %>
              <td class="follow_<%= user.id %>">
                <%= render 'follow', user: user %>
              </td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/withdraw.js.erb
$(".user_index").html("<%= j(render 'users/user_index', users: @users ) %>");