config/routes.rb
Rails.application.routes.draw do
  # デバイス用のルーティング
  devise_for :users
  # ルートパス
  root 'homes#top'
  get '/about' => 'homes#about'
  # ユーザーのルーティング
  # relationを入れ子構造に
  get 'users/sort' => 'users#sort'
  resources :users, only:[:index, :show, :edit, :update] do
    resources :relations, only:[:create, :destroy]
  end
  put '/users/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'
  put '/users/:id/back' => 'users#back', as: 'user_back'

  get 'museums/sort' => 'museums#sort'
  resources :museums do
    resources :posts, only:[:create, :edit, :update, :destroy] do
      resources :favorites, only:[:create, :destroy]
    end
    resources :recommends, only:[:create, :destroy]
    resources :visits, only:[:create, :destroy]
  end
  get 'map' => 'museums#map'

  resources :genres, only:[:create, :index, :destroy]

  resources :forums, only:[:create, :index, :show, :destroy] do
    resources :forum_posts, only:[:create]
  end
  get 'forums/:id/chat' => 'forums#chat', as: 'forum_chat'
  post 'forums/:id/lock' => 'forums#lock', as: 'forum_lock'

  get 'search' => 'searches#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/museum.rb
class Museum < ApplicationRecord

# ↓バリデーション
  # validates :appearance_image_id, presence: true
  validates :name, presence: true
  validates :genre_id, presence: true
  validates :opening_time, presence: true
  validates :closing_time, presence: true
  validates :regular_holiday, presence: true
  validates :prefecture, presence: true
  validates :address, presence: true
  validates :entrance_fee, presence: true
# ↑バリデーション
  attachment :appearance_image

# アソシエーション
  has_many :recommends, dependent: :destroy
  has_many :recommend_users, through: :recommends, source: :user
  has_many :visits, dependent: :destroy
  has_many :visit_users, through: :visits, source: :user
  has_many :posts, dependent: :destroy
  has_many :post_images, through: :posts
  has_many :notifications, dependent: :destroy
  belongs_to :user
  belongs_to :genre

  geocoded_by :location
  after_validation :geocode, if: :address_changed?

# regular_holidayの保存前に/[\[\]\"]/を""に変換
  before_save do
    self.regular_holiday.gsub!(/[\[\]\"]/, "") if attribute_present?("regular_holiday")
  end

# 県名選択時のenum
  enum prefecture: {
      "--県名を選択--": 0,
     北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
     茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
     新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
     岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24,
     滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
     鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35,
     徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
     福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46, 沖縄県: 47
  }

  def location
    "%s %s"%([self.prefecture, self.address])
  end


  def recommended_by?(user)
    recommends.where(user_id: user.id).exists?
  end

  def visited_by?(user)
    visits.where(user_id: user.id).exists?
  end

  def posted_by(user)
    posts.where(user_id: user.id)
  end

  def self.looks(searches, words)
    if searches == "perfect_match"
      @museum = Museum.where("name LIKE ?", "#{words}")
    elsif searches == "partial_match"
      @museum = Museum.where("name LIKE ?", "%#{words}%")
    end
  end

end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
  before_action :authenticate_user!, except:[:index, :show]
  before_action :set_museum, only:[:show, :edit, :update, :destroy]

  def new
    @museum = Museum.new
    @regular_holidays = ["月", "火", "水", "木", "金", "土", "日", "祝", "不定期", "なし", "不明"]
  end

  def create
    @museum = Museum.new(params_museum)
    @museum.user_id = current_user.id
    @museum.status = 1
    if @museum.save
      redirect_to museum_path(@museum.id)
    else
      @regular_holidays = ["月", "火", "水", "木", "金", "土", "日", "祝", "不定期", "なし", "不明"]
      render 'new'
    end
  end

  def show
    @post = Post.new
    @posts = Post.where(museum_id: params[:id]).order(id: "DESC").page(params[:page]).per(30)
    @post_images = @museum.post_images.order(id: "DESC")
  end

  def index
    @museums = Museum.order(:prefecture).page(params[:page]).per(20)
  end

  def edit
    @regular_holidays = ["月", "火", "水", "木", "金", "土", "日", "祝", "不定期", "なし", "不明"]
  end

  def update
    @museum.user_id = current_user.id
    @museum.status = 2
    if @museum.update(params_museum)
      redirect_to museum_path(@museum.id)
    else
      @regular_holidays = ["月", "火", "水", "木", "金", "土", "日", "祝", "不定期", "なし", "不明"]
      render 'edit'
    end
  end

  def destroy
    @museum.destroy
    redirect_to museums_path
  end

  def sort
    if params[:sort] == "prefecture"
      @museums = Museum.all.order(:prefecture)
      @sort = "prefecture"
    elsif params[:sort] == "recommend"
      @museums = Museum.all.sort{|a,b| b.recommend_users.count <=> a.recommend_users.count}
      @sort = "recommend"
    elsif params[:sort] == "visitor"
      @museums = Museum.all.sort{|a,b| b.visit_users.count <=> a.visit_users.count}
      @sort = "visitor"
    elsif params[:sort] == "comment"
      @museums = Museum.all.sort{|a,b| b.posts.count <=> a.posts.count}
      @sort = "comment"
    elsif params[:sort] == "picture"
      @museums = Museum.all.sort{|a,b| b.post_images.count <=> a.post_images.count}
      @sort = "picture"
    end
  end

  def map
    @map_museums = Museum.all.order(:prefecture)
    @museums = Museum.all.order(:prefecture).page(params[:page]).per(20)
  end

  private

  def params_museum
    params.require(:museum).permit(
      :appearance_image, :name, :genre_id, :prefecture, :address, :latitude, :longitude,
      :opening_time, :closing_time, :entrance_fee, :shop, :url, :regular_holiday => []
      )
  end

  def set_museum
    @museum = Museum.find(params[:id])
  end
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/views/museums/_post.html.erb
<div class="post-form">
  <div class="post-title d-flex">
    <div class="post-main_title"><strong><%= post.title %></strong></div>
    <div class="post-user">
      <%= link_to user_path(post.user.id) do %>
        <%= attachment_image_tag post.user, :profile_image, size:"40x40", format:"jpeg", fallback:"no_image.png", class:"circle-image" %>
      <% end %>
      <%= post.user.name %>
    </div>
  </div>
  <div class="post-body">
    <%= post.body %><br/>
    <!--画像が投稿されていた場合に画像表示-->
    <% if post.post_images.present? %>
      <% post.post_images.each do |image| %>
        <%= attachment_image_tag image, :picture, size:"40x40", format:"jpeg" %>
      <% end %>
    <% end %>
  </div>
  <div class="post-detail d-flex">
    <div>
      <% if post.how_to_visit.present? %>
        <label>訪問方法：</label>
        <%= post.how_to_visit %>
      <% end %>
      <% if post.companion.present? %>
        <label>同伴者：</label>
        <%= post.companion %>
      <% end %>
    </div>
    <div class="post-day d-flex pl-2">
      <% if post.user == current_user %>
        <div class="mr-4">
          <label>投稿日：</label>
          <%= post.created_at.strftime('%Y/%m/%d') %>
        </div>
        <div class="mr-3">
          <i class="fas fa-heart fa-lg my-heart"></i>
          <%= post.favorites.count %>
        </div>
        <div class="mr-1">
          <%= link_to edit_museum_post_path(museum.id, post.id) do %>
            <i class="far fa-edit fa-lg"></i>
            編集
          <% end %>
        </div>
        <div>
          <%= link_to museum_post_path(museum.id, post.id), method: :delete, remote: true do %>
            <i class="far fa-trash-alt fa-lg"></i>
            削除
          <% end %>
        </div>
      <% else %>
        <div class="d-flex">
          <div class="mr-4">
            <label>投稿日：</label>
            <%= post.created_at.strftime('%Y/%m/%d') %>
          </div>
          <div>
            <% if post.favorited_by?(current_user) %>
              <%= link_to museum_post_favorite_path(museum.id, post.id, post.id), method: :delete, remote: true do %>
                <i class="fas fa-heart fa-lg like-heart"></i>
              <% end %>
              <%= post.favorites.count %>
            <% else %>
              <%= link_to museum_post_favorites_path(museum.id, post.id), method: :post, remote: true do %>
                <i class="far fa-heart fa-lg unlike-heart"></i>
              <% end %>
              <%= post.favorites.count %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/museums/_post_images.html.erb
<% if post_images.exists? %>
  <% post_images.each do |image| %>
    <%= attachment_image_tag image, :picture, size:"140x140", format:"jpeg" %>
  <% end %>
<% else %>
  <p>投稿された画像はありません！</p>
<% end %>

app/views/museums/_posts.html.erb
<% posts.each do |post| %>
  <% if post.user.is_deleted == false %>
    <!--コメント表示を部分テンプレート化-->
    <div class="post_<%= post.id %>">
      <%= render partial: 'museums/post', locals: {post: post, museum: museum} %>
    </div>
  <% end %>
<% end %>

app/views/museums/_recommend.html.erb
<% if museum.recommended_by?(current_user) %>
  <%= link_to museum_recommend_path(museum.id, museum.id), method: :delete, remote: true do %>
    <i class="fas fa-star fa-2x star"></i>
  <% end %>
<% else %>
  <%= link_to museum_recommends_path(museum.id), method: :post, remote: true do %>
    <i class="far fa-star fa-2x unchecked-star"></i>
  <% end %>
<% end %>
<%= museum.recommends.count %>

app/views/museums/_visit.html.erb
<% if museum.visited_by?(current_user) %>
  <%= link_to museum_visit_path(museum.id, museum.id), method: :delete, remote: true do %>
    <i class="fas fa-door-open fa-2x door"></i>
  <% end %>
<% else %>
  <%= link_to museum_visits_path(museum.id), method: :post, remote: true do %>
    <i class="fas fa-door-closed fa-2x unchecked-door"></i>
  <% end %>
<% end %>
<%= museum.visits.count %>

app/views/museums/edit.html.erb
<div class="page-title">
  <h3>
    <i class="fas fa-landmark"> 博物館編集</i>
    ～<%= @museum.name %>～
  </h3>
</div>

<%= render "layouts/error_messages", resource: @museum %>

<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <%= form_with model:@museum, local:true do |f| %>
      <table class="table table-borderless">
        <tr>
          <th>
            <%= f.label :appearance_image, '外観イメージ' %>
          </th>
          <td>
            <%= f.attachment_field :appearance_image %>
          </td>
        </tr>
        <tr>
          <th>
            <%= f.label :name, '博物館名' %>
          </th>
          <td>
            <%= f.text_field :name %>
          </td>
        </tr>
        <tr>
          <th>
            <%= f.label :genre_id, 'ジャンル' %>
          </th>
          <td>
            <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--" %>
          </td>
        </tr>
        <tr>
          <th>
            <%= f.label :'住所' %>
          </th>
          <td>
            <%= f.select :prefecture, Museum.prefectures.keys %>
            <%= f.text_field :address, placeholder:'県名以降を入力してください' %>
          </td>
        </tr>
        <tr>
          <th>
            <%= f.label :'営業時間' %>
          </th>
          <td>
            <%= f.time_field :opening_time %> ～ <%= f.time_field :closing_time %>
          </td>
        </tr>
        <tr>
          <th>
            <%= f.label :regular_holiday, '定休日' %>
          </th>
          <td>
            <% @regular_holidays.each do |r| %>
              <%= f.check_box :regular_holiday, {multiple: true}, r, nil %>
              <%= f.label :regular_holiday, r %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>
            <%= f.label :entrance_fee, '入場料' %>
          </th>
          <td>
            <%= f.text_field :entrance_fee %> 円
          </td>
        </tr>
        <tr>
          <th>
            <%= f.label :shop, 'ショップ' %>
          </th>
          <td>
            <%= f.radio_button :shop, true %>
            <%= f.label :shop, 'あり', value: true %>
            <%= f.radio_button :shop, false %>
            <%= f.label :shop, 'なし', value: false %>
          </td>
        </tr>
        <tr>
          <th>
            <%= f.label :url, '公式HP' %>
          </th>
          <td>
            <%= f.text_field :url, placeholder:'URLを入力してください' %>
          </td>
        </tr>
        <tr align="center">
          <td colspan="2">
            <%= f.submit '変更する！', class:"btn btn-success" %>
          </td>
          <td></td>
        </tr>
      </table>
    <% end %>
  </div>
  <div class="col-md-1"></div>
</div>

app/views/museums/index.html.erb
<div class="page-title d-flex">
  <h3 class="mr-3">
    <i class="fas fa-landmark"> 博物館一覧</i>
  </h3>
  <p><%= link_to '新規登録', new_museum_path, class:"btn btn-success" %></p>
  <p class="ml-3 mt-2"><%= link_to '>>全体Mapはこちらから！', map_path %></p>
  <% if user_signed_in? %>
    <% if current_user.admin? %>
      <p class="ml-3"><%= link_to 'ジャンル新規登録', genres_path, class:"btn btn-primary" %></p>
    <% end %>
  <% end %>
</div>

<%= form_with url: museums_sort_path, method: :get, local: true do |f| %>
  <%= f.select :sort,
  [['都道府県順','prefecture'],
   ['訪問数が多い順','visitor'],
   ['おすすめが多い順','recommend'],
   ['コメント数が多い順','comment'],
   ['写真数が多い順','picture']]
   %>
   <%= f.submit '並びかえる' %>
<% end %>

<div class="row">
  <table class="table">
    <thead>
      <tr align="center">
        <th></th>
        <th></th>
        <th>所在地</th>
        <th>ジャンル</th>
        <th>訪問人数</th>
        <th>おすすめ</th>
        <th>コメント</th>
        <th>写真数</th>
      </tr>
    </thead>
    <tbody>
      <% @museums.each do |museum| %>
      <tr align="center">
        <td>
          <% if user_signed_in? %>
            <% if museum.recommended_by?(current_user) %>
              <i class="fas fa-star star"></i>
            <% elsif museum.visited_by?(current_user) %>
              <i class="fas fa-door-open door"></i>
            <% end %>
          <% end %>
        </td>
        <td align="left">
          <%= attachment_image_tag museum, :appearance_image, size:"40x40", format:"jpeg" %>
          <%= link_to museum.name, museum_path(museum.id) %>
        </td>
        <td><%= museum.prefecture %></td>
        <td><%= museum.genre.name %></td>
        <td><%= museum.visits.count %>人</td>
        <td><%= museum.recommends.count %>人</td>
        <td><%= museum.posts.count %>件</td>
        <td>
          <% sum = 0 %>
          <% museum.posts.each do |post| %>
            <% sum += post.post_images.count %>
          <% end %>
          <%= sum %> 枚
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @museums %>

app/views/museums/map.html.erb
<div class="page-title">
  <h3>
    <i class="fas fa-map-marked-alt"> 全体マップ</i>
  </h3>
</div>

<div class="mb-3">
  <!--検索フォーム-->
  <input id="address" type="textbox">
  <input type="button" value="検索" onclick="codeAddress()" class="btn btn-success">
</div>

<div class="row">
  <div class="col-md-4">
    <table class="table">
      <thead>
        <tr align="center">
          <th>施設名</th>
          <th>おすすめ</th>
          <th>訪問数</th>
        </tr>
      </thead>
      <tbody>
        <% @museums.each do |museum| %>
          <tr align="center">
            <td><%= museum.name %></td>
            <td><%= museum.recommends.count %></td>
            <td><%= museum.visits.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @museums %>
  </div>

  <div class="col-md-8">
    <!--地図表示-->
    <div id='map'></div>
      <style>
        #map {
          height: 450px ;
          width: 700px ;
        }
      </style>
    <script>
      let geocoder
        function codeAddress(){
          let inputAddress = document.getElementById('address').value;

          geocoder.geocode( { 'address': inputAddress}, function(results, status) {
            if (status == 'OK') {
              map.setCenter(results[0].geometry.location);
              var marker = new google.maps.Marker({
                  map: map,
                  position: results[0].geometry.location
              });
            } else {
              alert('該当する結果がありませんでした：' + status);
            }
          });
        }

      let map
        function initMap(){
          geocoder = new google.maps.Geocoder()

          map = new google.maps.Map(document.getElementById('map'), {
              center: {lat: 38.258595, lng:137.6850225},
              zoom: 5,
          });

          <% @map_museums.each do |m| %>
              (function(){
              var contentString = "<%= m.name %>";

              var marker = new google.maps.Marker({
                  position:{lat: <%= m.latitude %>, lng: <%= m.longitude %>},
                  map: map,
                  title: contentString
              });
              // 情報ウィンドウ(吹き出し)の定義
              // 投稿の詳細ページへのリンクも
              var infowindow = new google.maps.InfoWindow({
              position: {lat: <%= m.latitude %>, lng: <%= m.longitude %>},
              content: contentString
              });
              // クリックしたときに情報ウィンドウを表示
              marker.addListener('click', function() {
              infowindow.open(map, marker);
              });
              })();
          <% end %>
          }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY']%>&callback=initMap" async defer></script>
  </div>
</div>

app/views/museums/show.html.erb
<div class="page-title">
  <h3>
    <i class="fas fa-landmark"> <%= @museum.name %></i>
  </h3>
</div>

<div class="row">
  <div class="museum-info col-md-3">
    <table class="museum-table">
      <!--博物館の外観画像-->
      <tr align="center">
        <th colspan="2"><%= attachment_image_tag @museum, :appearance_image, size:"80x80", format:'jpeg' %></th>
      </tr>
    　<!--博物館名-->
      <tr align="center">
        <th colspan="2" align="center"><%= @museum.name %></th>
      </tr>
    　<!--博物館のジャンル-->
      <tr>
        <th>ジャンル　　：</th>
        <td><%= @museum.genre.name %></td>
      </tr>
      <!--博物館の住所(リンク先はmap/index)-->
      <tr>
        <th>住所　　　　：</th>
        <td class="museum-address"><%= @museum.prefecture %><%= @museum.address %></td>
      </tr>
      <!--博物館の営業時間-->
      <tr>
        <th>営業時間　　：</th>
        <td><%= @museum.opening_time %> ～ <%= @museum.closing_time %></td>
      </tr>
      <!--博物館の定休日-->
      <tr>
        <th>定休日　　　：</th>
        <td><%= @museum.regular_holiday %></td>
      </tr>
      <!--博物館の入場料(大人)-->
      <tr>
        <th class="museum-address">入場料(大人) ：</th>
        <td><%= @museum.entrance_fee.to_s(:delimited) %>円</td>
      </tr>
      <!--博物館のショップの有無-->
      <tr>
        <th>ショップ　　：</th>
        <td>
          <% if @museum.shop == true %>
            <span>あり</span>
          <% else %>
            <span>なし</span>
          <% end %>
        </td>
      </tr>
      <!--博物館の公式HPの有無とURL-->
      <tr>
        <th>公式ＨＰ　　：</th>
        <td>
          <% if @museum.url != "" %>
            <%= link_to 'あり', @museum.url %>
          <% else %>
            <span>なし</span>
          <% end %>
        </td>
      </tr>
    </table>

      <!--以下はログイン状態でないと表示しない-->
    <% if user_signed_in? %>
      <table class="museum-button mt-3">
        <!--おすすめボタンと訪問済みボタン-->
        <tr align="center">
          <th class="recommend">
            <%= render 'recommend', museum: @museum %>
          </th>
          <th> </th>
          <th class="visit">
            <%= render 'visit', museum: @museum %>
          </th>
        </tr>
        <tr align="center">
          <td>
            おすすめ！
          </td>
          <td> </td>
          <td>
            行った！
          </td>
        </tr>
      </table>
        <!--編集ボタン(誰でも編集可能)-->
      <table class="museum-edit_destroy mt-3">
        <tr align="center">
          <th>
            <%= link_to edit_museum_path(@museum.id), class:"btn btn-primary" do %>
              <i class="fas fa-edit"></i>
              編集
            <% end %>
          </th>
          <th> </th>
          <th>
            <% if current_user.admin? %>
              <%= link_to museum_path(@museum.id), method: :delete, class:"btn btn-danger ml-3" do %>
                <i class="fas fa-trash"></i>
                削除
              <% end %>
            <% end %>
          </th>
        </tr>
      </table>
    <% end %>
  </div>

  <div class="col-md-9">
    <ul id="tab-menu" class="mb-0">
      <li><a href="#top" class="active">コメント</a></li>
      <li><a href="#post-image" class="">アルバム</a></li>
    </ul>
    <div id="tab-contents">
      <% if user_signed_in? %>
        <div id="top" class="tab">
          <!--コメント投稿フォームの表示/非表示ボタン-->
          <input type="button" value="＋コメント投稿" id="post-button" class="btn btn-primary mb-2">
          <div class="posts-form" id="post-form">
            <!--コメント投稿フォーム-->
            <%= form_with model:@post, url:museum_posts_path(@museum.id) do |f| %>
              <div class="posts-title">
                <strong><%= f.label :title, 'タイトル', class:"mr-3" %></strong>
                <%= f.text_field :title, size:"30" %>
              </div>
              <div class="posts-body">
                <strong><%= f.label :body, '本文', class:"mr-3" %></strong>
                <%= f.text_area :body, size:"90" %><br/>
                <strong><%= f.label :post_images_pictures, '写真', class:"mr-3" %></strong>
                <%= f.attachment_field :post_images_pictures, multiple: true %>
              </div>
              <div class="posts-form-detail d-flex">
                <span class="mr-3">
                  <strong><%= f.label :how_to_visit, '訪問方法' %></strong>
                  <% Post.how_to_visits.keys.each do |h| %>
                    <%= f.radio_button :how_to_visit, h %>
                    <%= f.label :how_to_visit, h %>
                  <% end %>
                </span>
                <span>
                  <strong><%= f.label :companion, '同伴者' %></strong>
                  <% Post.companions.keys.each do |c| %>
                    <%= f.radio_button :companion, c %>
                    <%= f.label :companion, c %>
                  <% end %>
                </span>
                <div>
                  <%= f.submit '投稿する！', class:"btn btn-success" %>
                </div>
              </div>
            <% end %>
          </div>
          <!--コメント表示-->
          <div class="post_index">
            <%= render partial: 'museums/posts', locals: {posts: @posts, museum: @museum} %>
          </div>
        </div>
        <div id="post-image" class="tab">
          <div class="post_image_index">
            <%= render partial: 'museums/post_images', locals: {post_images: @post_images} %>
          </div>
        </div>
      <% else %>
        <strong><p class="mt-3">　ログイン後ご覧いただけます！</p></strong>
      <% end %>
    </div>
  </div>
</div>

app/views/museums/sort.html.erb
<div class="page-title d-flex">
  <h3>
    <i class="fas fa-landmark"> 博物館一覧</i>
  </h3>
  <p class="mr-3 mt-2">
    (<% if @sort == "prefecture" %>
      都道府県順
    <% elsif @sort == "visitor" %>
      訪問数が多い順
    <% elsif @sort == "recommend" %>
      おすすめが多い順
    <% elsif @sort == "comment" %>
      コメント数が多い順
    <% elsif @sort == "picture" %>
      写真数が多い順
    <% end %>)
  </p>
  <p><%= link_to '新規登録', new_museum_path, class:"btn btn-success" %></p>
</div>

<%= form_with url: museums_sort_path, method: :get, local: true do |f| %>
  <%= f.select :sort,
  [['都道府県順','prefecture'],
   ['訪問数が多い順','visitor'],
   ['おすすめが多い順','recommend'],
   ['コメント数が多い順','comment'],
   ['写真数が多い順','picture']]
   %>
   <%= f.submit '並びかえる' %>
<% end %>

<div class="row">
  <table class="table">
    <thead>
      <tr align="center">
        <th></th>
        <th></th>
        <th>所在地</th>
        <th>ジャンル</th>
        <th>訪問人数</th>
        <th>おすすめ</th>
        <th>コメント</th>
        <th>写真数</th>
      </tr>
    </thead>
    <tbody>
      <% @museums.each do |museum| %>
      <tr align="center">
        <td>
          <% if user_signed_in? %>
            <% if museum.recommended_by?(current_user) %>
              <i class="fas fa-star star"></i>
            <% elsif museum.visited_by?(current_user) %>
              <i class="fas fa-door-open"></i>
            <% end %>
          <% end %>
        </td>
        <td align="left">
          <%= attachment_image_tag museum, :appearance_image, size:"40x40", format:"jpeg" %>
          <%= link_to museum.name, museum_path(museum.id) %>
        </td>
        <td><%= museum.prefecture %></td>
        <td><%= museum.genre.name %></td>
        <td><%= museum.visits.count %>人</td>
        <td><%= museum.recommends.count %>人</td>
        <td><%= museum.posts.count %>件</td>
        <td>
          <% sum = 0 %>
          <% museum.posts.each do |post| %>
            <% sum += post.post_images.count %>
          <% end %>
          <%= sum %> 枚
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>